name: CodeScan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '19 5 * * 3'

permissions:
  contents: read

jobs:
  CodeScan:
    permissions:
      contents: read
      security-events: write
      actions: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Cache files
        uses: actions/cache@v3
        with:
          path: |
            ~/.sonar
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Setup Go environment
        uses: actions/setup-go@v5.3.0
        with:
          go-version: '1.x' # specify the version of Go you need
      - name: CodeScan Scanner
        uses: codescan-io/codescan-scanner-action@1.6
        with:
          organization: ${{ secrets.CODESCAN_ORGANIZATION_KEY }}
          projectKey: ${{ secrets.CODESCAN_PROJECT_KEY }}
          login: ${{ secrets.CODESCAN_AUTH_TOKEN }}
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: codescan.sarif
